### ISSUE TITLE
Button TextStyle not editable .

### ISSUE THREAD

**Issue by bmarwa** [Ethiel97/nice_button#3]
Hi, can you add an option to set the text style to the button text. 

```
TextStyle(
      fontFamily: 'Montserrat',
      color: textColor,
      fontSize: fontSize,
      fontWeight: FontWeight.bold);
```

**Comment by ScottishRoss** [comment]
Is there a way to change the FontFamily for these buttons? It doesn't seem to inherit the FontFamily of MaterialApp?
